name: Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Start Octoprint
        run: |
          cd __tests__/octoprint
          docker-compose up -d
          cd ../..
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
